spring.application.name=${SPRING_APPLICATION_NAME:web}

# ===============================
# Database
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# ===============================
# Owner
# ===============================
owner.ownerName=${OWNER_NAME}
owner.ownerEmail=${OWNER_EMAIL}
owner.ownerPassword=${OWNER_PASSWORD}

# ===============================
# File Upload
# ===============================
file.upload-dir=${FILE_UPLOAD_DIR:uploads}